# Generated by Django 5.1.5 on 2025-01-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkapp', '0005_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_description', models.CharField(max_length=200)),
            ],
        ),
    ]
