# Generated by Django 5.1.5 on 2025-01-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkapp', '0007_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='type_description',
            field=models.CharField(choices=[('Seminar', 'Seminar'), ('Webinar', 'Webinar'), ('Workshop', 'Workshop')], default='Seminar', max_length=50),
        ),
    ]
