# Generated by Django 5.1.5 on 2025-01-25 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkapp', '0009_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('relieved_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='role_documents/')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparkapp.employee')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparkapp.role')),
            ],
        ),
    ]
