# Generated by Django 5.1.5 on 2025-01-25 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkapp', '0011_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_link', models.FileField(blank=True, null=True, upload_to='participation_docs/')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparkapp.employee')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparkapp.event')),
            ],
        ),
    ]
