# Generated by Django 4.2.11 on 2025-01-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparkapp', '0014_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
