# Generated by Django 4.2.11 on 2025-01-30 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkapp', '0015_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phn_no',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='from_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_date',
            field=models.DateTimeField(),
        ),
    ]
