# Generated by Django 5.1.5 on 2025-01-20 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('phn_no', models.CharField(max_length=15)),
                ('adhar_no', models.CharField(max_length=12, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('current_address', models.TextField()),
                ('residential_address', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparkapp.department')),
                ('designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparkapp.designation')),
            ],
        ),
    ]
