# Generated by Django 5.1.5 on 2025-01-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkapp', '0002_sampledata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleData',
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50),
        ),
    ]
