# Generated by Django 5.1.5 on 2025-01-25 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkapp', '0010_employeeroleassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparkapp.eventtype')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparkapp.venue')),
            ],
        ),
    ]
