# Generated by Django 5.1.5 on 2025-01-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkapp', '0012_eventparticipation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='type_description',
            field=models.CharField(max_length=100),
        ),
    ]
