# Generated by Django 4.2.11 on 2025-01-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparkapp', '0016_alter_employee_phn_no_alter_event_from_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipation',
            name='doc_link',
        ),
    ]
